version: '3'
networks:
  jasmine-net:
    driver: bridge
volumes:
    jasmine_prometheus_data: {}
    jasmine_grafana_data: {}
services:
  jasmine:
    image: giuseppe007/jasmine:local
    container_name: jasmine-main
    ports:
      - "2112"
    networks:
      - jasmine-net
    environment:
      - JASMINE_JIRASERVER=${JASMINE_JIRASERVER}
      - JASMINE_JIRAUSER=${JASMINE_JIRAUSER}
      - JASMINE_JIRAAPIKEY=${JASMINE_JIRAAPIKEY}
    volumes:
      - ../configs/jasmine/config.yaml:/config.yaml:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: jasmine-prom
    volumes:
      - jasmine_prometheus_data:/prometheus
      - ../configs/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=31d'
      - '--web.enable-lifecycle'
    # restart: unless-stopped
    ports:
      - "9090"
    networks:
      - jasmine-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: jasmine-grafana
    #restart: unless-stopped
    volumes:
      - jasmine_grafana_data:/var/lib/grafana
      - ../configs/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000"
    networks:
      - jasmine-net